## 1. Импорт зависимостей

In [41]:
import sys
from pathlib import Path
import polars as pl
import pandas as pd
import json
from hydra import compose, initialize_config_dir
from omegaconf import OmegaConf
from match import CONFIG_DIR, resolve_project_path

with initialize_config_dir(version_base=None, config_dir=str(CONFIG_DIR)):
    cfg = compose(config_name="prepare_data")

pl.Config.set_tbl_rows(-1)       # показывать все строки
pl.Config.set_tbl_cols(-1)       # показывать все столбцы
pl.Config.set_fmt_str_lengths(1000)  # не обрезать длинные строки
pl.Config.set_tbl_width_chars(200)   # ширина таблицы

polars.config.Config

## 2. Чтение конфига

In [27]:
cfg

{'path': {'items_human_path': 'data/items_human_normalized.parquet', 'matches_human_path': 'data/matches.parquet', 'items_human_normalized_path': 'data/items_human_normalized.parquet'}}

## 3. Чтение датасета

In [39]:
project = Path.cwd().parent
items_human_path = project / Path(cfg["path"]["items_human_path"])
matches_human_path = project / Path(cfg["path"]["matches_human_path"])
df_human = pl.read_parquet(items_human_path)
df_matches = pl.read_parquet(matches_human_path)
df_human, df_matches

(shape: (711_304, 5)
 ┌──────────────┬──────────────────────────────────────────────────────┬──────────────────────────────────────────────────────┬───────────────────┬─────────────────────────────────────────────────────┐
 │ id           ┆ name                                                 ┆ attributes                                           ┆ category          ┆ normalized_attributes                               │
 │ ---          ┆ ---                                                  ┆ ---                                                  ┆ ---               ┆ ---                                                 │
 │ i64          ┆ str                                                  ┆ str                                                  ┆ str               ┆ str                                                 │
 ╞══════════════╪══════════════════════════════════════════════════════╪══════════════════════════════════════════════════════╪═══════════════════╪═════════════════════════════════════════════════════╡
 │ 197          ┆ victor reinz прокладка впускного коллектора арт.     ┆ {"артикул":"703315700","бренд":"victor               ┆ Автотовары        ┆ {"артикул": "703315700", "бренд": "victor reinz",   │
 │              ┆ 703315700                                            ┆ reinz","партномер (артикул                           ┆                   ┆ "партномер (артикул производителя)": "703315700",   │
 │              ┆                                                      ┆ производителя)":"703315700","тип":"прокладка         ┆                   ┆ "тип": "прокладка двигателя", "тип системы":        │
 │              ┆                                                      ┆ двигателя","вид техники":"легковые автомобили"}      ┆                   ┆ "легковые автомобили"}                              │
 │ 415          ┆ stellox диск тормозной, арт. 8500892sx               ┆ {"артикул":"stellox_8500892sx","место                ┆ Автотовары        ┆ {"артикул": "stellox_8500892sx", "система           │
 │              ┆                                                      ┆ установки":"передние","толщина тормозного диска,     ┆                   ┆ установки": "передние", "толщина тормозного диска,  │
 │              ┆                                                      ┆ мм":"28","бренд":"stellox","oem-номер":"3050086;     ┆                   ┆ мм": "28", "бренд": "stellox", "oem-номер":         │
 │              ┆                                                      ┆ a9064210012; 2e0615301; 68006716aa; 9064210012;      ┆                   ┆ "3050086; a9064210012; 2e0615301; 68006716aa;       │
 │              ┆                                                      ┆ 9064210212; 9064210012s; 9064210112","партномер      ┆                   ┆ 9064210012; 9064210212; 9064210012s; 9064210112",   │
 │              ┆                                                      ┆ (артикул производителя)":"8500892sx","тип":"диск     ┆                   ┆ "партномер (артикул производителя)": "8500892sx",   │
 │              ┆                                                      ┆ тормозной","тип тормозного                           ┆                   ┆ "тип": "диск тормозной", "тип тормозного диска":    │
 │              ┆                                                      ┆ диска":"вентилируемый","вид техники":"легковые       ┆                   ┆ "вентилируемый", "тип системы": "легковые           │
 │              ┆                                                      ┆ автомобили"}                                         ┆                   ┆ автомобили"}                                        │
 │ 427          ┆ комплект подшипника ступицы колеса lynxauto          ┆ {"артикул производителя":"","бренд":"lynxauto","прим ┆ Автотовары        ┆ {"артикул производителя": "", "бренд": "lynxauto",  │
 │              ┆                                                      ┆ ечание":"внешний вид изделия может отличаться от     ┆                   ┆ "примечание": "внешний вид изделия может отличаться │
 │              ┆                                                      ┆ фотографий","цена за":"1 шт.","код                   ┆                   ┆ от фотографий", "плата за": "1 шт.", "код товара":  │
 │              ┆                                                      ┆ товара":"600000256748"}                              ┆                   ┆ "600000256748"}                                     │
 │ 1027         ┆ kraft подшипник ступицы, арт. kt204632, 1 шт.        ┆ {"артикул":"112097-01","бренд":"kraft","количество в ┆ Автотовары        ┆ {"артикул": "112097-01", "бренд": "kraft",          │
 │              ┆                                                      ┆ упаковке, шт":"1","партномер (артикул                ┆                   ┆ "количество в упаковке, шт": "1", "партномер        │
 │              ┆                                                      ┆ производителя)":"kt204632","тип":"подшипник          ┆                   ┆ (артикул производителя)": "kt204632", "тип":        │
 │              ┆                                                      ┆ ступицы"}                                            ┆                   ┆ "подшипник ступицы"}                                │
 │ 2639         ┆ фильтр салонный skoda fabia 00-                      ┆ {"альтернативные артикулы товара":"8104400xkz96a;500 ┆ Автотовары        ┆ {"альтернативные артикулы товара": "8104400xkz96a;5 │
 │              ┆                                                      ┆ 13702;ac0110c;50013941;9.7.84;la120;if-3019;afc1076; ┆                   ┆ 0013702;ac0110c;50013941;9.7.84;la120;if-3019;afc10 │
 │              ┆                                                      ┆ ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987 ┆                   ┆ 76;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123; │
 │              ┆                                                      ┆ 432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c ┆                   ┆ 1987432057;1010-026;6q0819653;6q0819653b;9.7.147;ac │
 │              ┆                                                      ┆ ;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb989 ┆                   ┆ 0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076 │
 │              ┆                                                      ┆ 2c;fcr21f061;jdacx055;lac-1006;7110221sx;7110247sx;1 ┆                   ┆ ;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;7110 │
 │              ┆                                                      ┆ cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q0 ┆                   ┆ 247sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543s │
 │              ┆                                                      ┆ 820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf04 ┆                   ┆ x;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6 │
 │              ┆                                                      ┆ 1;pf2041;lac1006c;8104400xkz96a\n","артикул":"cu2545 ┆                   ┆ 123;1cf041;pf2041;lac1006c;8104400xkz96a",          │
 │              ┆                                                      ┆ ","бренд":"sat","страна-изготовитель":"китай","oem-н ┆                   ┆ "артикул": "cu2545", "бренд": "sat",                │
 │              ┆                                                      ┆ омер":"8104400xkz96a;50013702;ac0110c;50013941;9.7.8 ┆                   ┆ "страна-производитель": "китай", "oem-номер": "8104 │
 │              ┆                                                      ┆ 4;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;f ┆                   ┆ 400xkz96a;50013702;ac0110c;50013941;9.7.84;la120;if │
 │              ┆                                                      ┆ s089;lak120;sab 123;1987432057;1010-026;6q0819653;6q ┆                   ┆ -3019;afc1076;ac9403;ca-49010;6q0820367b;fs089;lak1 │
 │              ┆                                                      ┆ 0819653b;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if30 ┆                   ┆ 20;sab 123;1987432057;1010-026;6q0819653;6q0819653b │
 │              ┆                                                      ┆ 19p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac-10 ┆                   ┆ ;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1 │
 │              ┆                                                      ┆ 06;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545 ┆                   ┆ 123;afw1076;gb9892c;fcr21f061;jdacx055;lac-1006;711 │
 │              ┆                                                      ┆ ;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf21 ┆                   ┆ 0221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;wc40 │
 │              ┆                                                      ┆ 23;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz ┆                   ┆ 15;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;m │
 │              ┆                                                      ┆ 96a\n","комплектация":"фильтр салона для авто 1      ┆                   ┆ c-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a │
 │              ┆                                                      ┆ шт","партномер (…                                    ┆                   ┆ ", "комплект": "фильтр салона для авто 1 шт",       │
 │              ┆                                                      ┆                                                      ┆                   ┆ "партно…                                            │
 │ …            ┆ …                                                    ┆ …                                                    ┆ …                 ┆ …                                                   │
 │ 850403682391 ┆ подвеска из серебра с керамикой/фианитом diamant     ┆ {"бренд":"diamant","артикул производителя":"94-130-0 ┆ Ювелирные изделия ┆ {"бренд": "diamant", "артикул производителя":       │
 │              ┆ 94-130-00573-1                                       ┆ 0573-1","модель":"94-130-00573-1","тип":"подвеска"," ┆                   ┆ "94-130-00573-1", "модель": "94-130-00573-1",       │
 │              ┆                                                      ┆ вид":"медальон","пол":"женский","материал изделия":" ┆                   ┆ "тип": "подвеска", "пол": "женский", "материал      │
 │              ┆                                                      ┆ серебро","проба":"925","вставка":"керамика;          ┆                   ┆ изделия": "серебро", "проба": "925", "вставка":     │
 │              ┆                                                      ┆ фианит","количество карат":"0","средний вес изделия, ┆                   ┆ "керамика; фианит", "количество карат": "0",        │
 │              ┆                                                      ┆ г":"1,11","цвет материала":"серебристый","цвет       ┆                   ┆ "средний вес изделия, г": "1,11", "цвет материала": │
 │              ┆                                                      ┆ вставки":"белый; прозрачный","изображение/надпись":" ┆                   ┆ "серебристый", "цвет вставки": "белый; прозрачный", │
 │              ┆                                                      ┆ рак","страна-производитель":"россия","код            ┆                   ┆ "изображение/надпись": "рак",                       │
 │              ┆                                                      ┆ товара":"100028549068"}                              ┆                   ┆ "страна-производитель": "россия", "код товара":     │
 │              ┆                                                      ┆                                                      ┆                   ┆ "100028549068"}                                     │
 │ 850403682539 ┆ sokolov, серьги из комбинированного золота с         ┆ {"целевая аудитория":"взрослая","артикул":"1022068", ┆ Ювелирные изделия ┆ {"целевая аудитория": "взрослая", "артикул":        │
 │              ┆ бриллиантами, 1022068, декоративные, 585 проба       ┆ "бренд":"sokolov","бриллиант":"10 бр круг 17         ┆                   ┆ "1022068", "бренд": "sokolov", "бриллиант": "10 бр  │
 │              ┆                                                      ┆ 1,00*1,10","как читать характеристику                ┆                   ┆ круг 17 1,00*1,10", "как читать свойство            │
 │              ┆                                                      ┆ бриллианта":"на примере \"1 бр. кр-57-0.26 6/6а\"    ┆                   ┆ бриллианта": "на примере \"1 бр. кр-57-0.26 6/6а\"  │
 │              ┆                                                      ┆ расшифровываются параметры так: 1 бр. – число        ┆                   ┆ расшифровываются параметры так: 1 бр. – число       │
 │              ┆                                                      ┆ бриллиантов. кр-57 – форма огранки и число граней    ┆                   ┆ бриллиантов. кр-57 – форма огранки и число граней   │
 │              ┆                                                      ┆ (\"кр\" - \"круглая\"). 0.26 – масса бриллианта в    ┆                   ┆ (\"кр\" - \"круглая\"). 0.26 – масса бриллианта в   │
 │              ┆                                                      ┆ каратах. 6/6 – цвет/чистота бриллианта (зависит от   ┆                   ┆ каратах. 6/6 – цвет/чистота бриллианта (зависит от  │
 │              ┆                                                      ┆ количества граней: \"1/1\" – бесцветный идеальной    ┆                   ┆ количества граней: \"1/1\" – бесцветный идеальной   │
 │              ┆                                                      ┆ чистоты; последнее значение цвета может быть \"4\"   ┆                   ┆ чистоты; последнее значение цвета может быть \"4\"  │
 │              ┆                                                      ┆ или \"7\" (коричневый), последнее значение чистоты – ┆                   ┆ или \"7\" (коричневый), последнее значение чистоты  │
 │              ┆                                                      ┆ \"6\", \"9\" или \"12\" (много дефектов, низкая      ┆                   ┆ – \"6\", \"9\" или \"12\" (много дефектов, низкая   │
 │              ┆                                                      ┆ прозрачность). а – качество огранки (значения от     ┆                   ┆ прозрачность). а – качество огранки (значения от    │
 │              ┆                                                      ┆ \"а\" до \"г\").","коллекция":"базовая               ┆                   ┆ \"а\" до \"г\").", "коллекция": "базовая            │
 │              ┆                                                      ┆ коллекция","страна-изготовитель":"россия","размеры,  ┆                   ┆ коллекция", "страна-производитель": "россия",       │
 │              ┆                                                      ┆ мм":"2х2х14","вставка":"бриллиант","вес основных     ┆                   ┆ "размеры, мм": "2х2х14", "вставка": "бриллиант",    │
 │              ┆                                                      ┆ вставок, карат":"0.054","детские                     ┆                   ┆ "вес основных вставок, карат": "0.054", "детские    │
 │              ┆                                                      ┆ украшения":"нет","длина украшения, см":"1.4","вид    ┆                   ┆ украшения": "нет", "длина украшения, см": "1.4",    │
 │              ┆                                                      ┆ замка":"английский","проба":"585","модель            ┆                   ┆ "тип замка": "английский", "проба": "585", "модель  │
 │              ┆                                                      ┆ сережек":"дорожки","комплектация":"серьги, бирка,    ┆                   ┆ сережек": "дорожки", "комплект": "серьги, бирка,    │
 │              ┆                                                      ┆ пломба, подарочная упаковка","упаковка":"подарочная  ┆                   ┆ пломба, подарочная упаковка", …                     │
 │              ┆                                                      ┆ …                                                    ┆                   ┆                                                     │
 │ 850403682571 ┆ кольцо из серебра р. 20 lazurit-online 8634yg,       ┆ {"модель":"8634yg","артикул производителя":"8634yg20 ┆ Ювелирные изделия ┆ {"модель": "8634yg", "артикул производителя":       │
 │              ┆ хромдиопсид                                          ┆ 0","бренд":"lazurit-online","тип":"кольцо","вид":"кл ┆                   ┆ "8634yg200", "бренд": "lazurit-online", "тип":      │
 │              ┆                                                      ┆ ассическое","пол":"женский","материал изделия":"сере ┆                   ┆ "кольцо", "пол": "женский", "материал изделия":     │
 │              ┆                                                      ┆ бро","проба":"925","вставка":"хромдиопсид","количест ┆                   ┆ "серебро", "проба": "925", "вставка":               │
 │              ┆                                                      ┆ во карат":"0,75","размер":"20","средний вес изделия, ┆                   ┆ "хромдиопсид", "количество карат": "0,75",          │
 │              ┆                                                      ┆ г":"1,47","цвет материала":"золотистый","цвет        ┆                   ┆ "количество": "20", "средний вес изделия, г":       │
 │              ┆                                                      ┆ вставки":"зеленый","форма вставки":"капля","тип      ┆                   ┆ "1,47", "цвет материала": "золотистый", "цвет       │
 │              ┆                                                      ┆ огранки":"груша","покрытие":"золочение","особенности ┆                   ┆ вставки": "зеленый", "форма вставки": "капля", "тип │
 │              ┆                                                      ┆ дизайна":"без особенностей","изображение/надпись":"н ┆                   ┆ огранки": "груша", "покрытие": "золочение",         │
 │              ┆                                                      ┆ ет","страна-производитель":"россия","коллекция":"кол ┆                   ┆ "особенности дизайна": "без особенностей",          │
 │              ┆                                                      ┆ лекция дуэт","код товара":"100056726243"}            ┆                   ┆ "изображение/надпись": "нет",                       │
 │              ┆                                                      ┆                                                      ┆                   ┆ "страна-производитель": "россия", "коллекция":      │
 │              ┆                                                      ┆                                                      ┆                   ┆ "коллекция дуэт", "код товара": "100056726243"}     │
 │ 850403682699 ┆ silver fish кольцо с "сапфиром" радированное серебро ┆ {"целевая аудитория":"взрослая","артикул":"10-0217   ┆ Ювелирные изделия ┆ {"целевая аудитория": "взрослая", "артикул":        │
 │              ┆ 925 (размер кольца 16,5) 8 марта (подарок)           ┆ сапoz_16,5","бренд":"silver                          ┆                   ┆ "10-0217 сапoz_16,5", "бренд": "silver fish",       │
 │              ┆                                                      ┆ fish","коллекция":"базовая коллекция","цвет товара": ┆                   ┆ "коллекция": "базовая коллекция", "цвет товара":    │
 │              ┆                                                      ┆ "серебристый","страна-изготовитель":"россия","о      ┆                   ┆ "серебристый", "страна-производитель": "россия", "о │
 │              ┆                                                      ┆ драгоценном металле":"серебро - серебряные           ┆                   ┆ драгоценном металле": "серебро - серебряные         │

## 3.2 Разбор карточек которые совпадают

In [29]:
df_matches.filter(pl.col("target") == 1).head()

shape: (5, 3)
┌─────┬──────────────┬────────┐
│ id1 ┆ id2          ┆ target │
│ --- ┆ ---          ┆ ---    │
│ i64 ┆ i64          ┆ f64    │
╞═════╪══════════════╪════════╡
│ 476 ┆ 841813632218 ┆ 1.0    │
│ 525 ┆ 13777        ┆ 1.0    │
│ 622 ┆ 360777364649 ┆ 1.0    │
│ 706 ┆ 352187426187 ┆ 1.0    │
│ 753 ┆ 747324374388 ┆ 1.0    │
└─────┴──────────────┴────────┘

In [125]:
row = df_matches.filter(pl.col("target") == 1).sample(1)
id1, id2 = row.select("id1", "id2").row(0)


item1 = (
    df_human
    .filter(pl.col("id") == id1)
    .select("id", "name", "normalized_attributes")
    .row(0, named=True)
)

item2 = (
    df_human
    .filter(pl.col("id") == id2)
    .select("id", "name", "normalized_attributes")
    .row(0, named=True)
)


attrs1 = json.loads(item1["normalized_attributes"])
attrs2 = json.loads(item2["normalized_attributes"])

all_keys = sorted(set(attrs1) | set(attrs2))


names = pl.DataFrame({
    "id": [item1["id"], item2["id"]],
    "name": [item1["name"], item2["name"]],
})

comparison = (
    pl.DataFrame({
        "attribute": all_keys,
        f"value_{id1}": [attrs1.get(key) for key in all_keys],
        f"value_{id2}": [attrs2.get(key) for key in all_keys],
    })
    .with_columns(
        (
            pl.col(f"value_{id1}").fill_null("<нет>")
            == pl.col(f"value_{id2}").fill_null("<нет>")
        ).alias("equal")
    )
    .sort(["equal", "attribute"], descending=[True, False])
)

display(names)
display(comparison)

shape: (2, 2)
┌──────────────┬─────────────────────────────────────────────────────────┐
│ id           ┆ name                                                    │
│ ---          ┆ ---                                                     │
│ i64          ┆ str                                                     │
╞══════════════╪═════════════════════════════════════════════════════════╡
│ 575525714050 ┆ lori / набор для творчества lori картина из пай         │
│ 326417531997 ┆ набор для творчества картина из пайеток единорог ап-047 │
└──────────────┴─────────────────────────────────────────────────────────┘

shape: (8, 4)
┌──────────────────────┬───────────────────────────┬────────────────────┬───────┐
│ attribute            ┆ value_575525714050        ┆ value_326417531997 ┆ equal │
│ ---                  ┆ ---                       ┆ ---                ┆ ---   │
│ str                  ┆ str                       ┆ str                ┆ bool  │
╞══════════════════════╪═══════════════════════════╪════════════════════╪═══════╡
│ бренд                ┆ null                      ┆ нет бренда         ┆ false │
│ валюта               ┆ rub                       ┆ null               ┆ false │
│ высота упаковки, мм  ┆ 40                        ┆ null               ┆ false │
│ длина упаковки, мм   ┆ 260                       ┆ null               ┆ false │
│ комплект             ┆ наборы для поделок - 1 шт ┆ null               ┆ false │
│ страна-производитель ┆ null                      ┆ россия             ┆ false │
│ тип                  ┆ null                      ┆ картина из пайеток ┆ false │
│ ширина упаковки, мм  ┆ 220                       ┆ null               ┆ false │
└──────────────────────┴───────────────────────────┴────────────────────┴───────┘

## 4. Дисбаланс класса 1/4

In [31]:
attrs = json.loads(df_human.filter(pl.col("id") == id1).select("attributes").to_series().to_list()[0])
attrs.keys()

dict_keys(['бренд', 'страна-изготовитель', 'единиц в одном товаре', 'тип'])

In [32]:
(
    df_matches
    .group_by("target")
    .agg(pl.count().alias("count"))
    .with_columns(
        (pl.col("count") / pl.sum("count")).alias("ratio")
    )
    .sort("target")
)

C:\Users\Samoylov_Nikita\AppData\Local\Temp\ipykernel_19472\3475110605.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("count"))

shape: (2, 3)
┌────────┬────────┬──────────┐
│ target ┆ count  ┆ ratio    │
│ ---    ┆ ---    ┆ ---      │
│ f64    ┆ u32    ┆ f64      │
╞════════╪════════╪══════════╡
│ 0.0    ┆ 271764 ┆ 0.743227 │
│ 1.0    ┆ 93890  ┆ 0.256773 │
└────────┴────────┴──────────┘

## 5. Разбор датасета товаров

In [33]:
df_human.head()

shape: (5, 5)
┌──────┬───────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────┬────────────┬──────────────────────────────────────────────────────────┐
│ id   ┆ name                                                      ┆ attributes                                                ┆ category   ┆ normalized_attributes                                    │
│ ---  ┆ ---                                                       ┆ ---                                                       ┆ ---        ┆ ---                                                      │
│ i64  ┆ str                                                       ┆ str                                                       ┆ str        ┆ str                                                      │
╞══════╪═══════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════╪════════════╪══════════════════════════════════════════════════════════╡
│ 197  ┆ victor reinz прокладка впускного коллектора арт.          ┆ {"артикул":"703315700","бренд":"victor reinz","партномер  ┆ Автотовары ┆ {"артикул": "703315700", "бренд": "victor reinz",        │
│      ┆ 703315700                                                 ┆ (артикул производителя)":"703315700","тип":"прокладка     ┆            ┆ "партномер (артикул производителя)": "703315700", "тип": │
│      ┆                                                           ┆ двигателя","вид техники":"легковые автомобили"}           ┆            ┆ "прокладка двигателя", "тип системы": "легковые          │
│      ┆                                                           ┆                                                           ┆            ┆ автомобили"}                                             │
│ 415  ┆ stellox диск тормозной, арт. 8500892sx                    ┆ {"артикул":"stellox_8500892sx","место                     ┆ Автотовары ┆ {"артикул": "stellox_8500892sx", "система установки":    │
│      ┆                                                           ┆ установки":"передние","толщина тормозного диска,          ┆            ┆ "передние", "толщина тормозного диска, мм": "28",        │
│      ┆                                                           ┆ мм":"28","бренд":"stellox","oem-номер":"3050086;          ┆            ┆ "бренд": "stellox", "oem-номер": "3050086; a9064210012;  │
│      ┆                                                           ┆ a9064210012; 2e0615301; 68006716aa; 9064210012;           ┆            ┆ 2e0615301; 68006716aa; 9064210012; 9064210212;           │
│      ┆                                                           ┆ 9064210212; 9064210012s; 9064210112","партномер (артикул  ┆            ┆ 9064210012s; 9064210112", "партномер (артикул            │
│      ┆                                                           ┆ производителя)":"8500892sx","тип":"диск тормозной","тип   ┆            ┆ производителя)": "8500892sx", "тип": "диск тормозной",   │
│      ┆                                                           ┆ тормозного диска":"вентилируемый","вид техники":"легковые ┆            ┆ "тип тормозного диска": "вентилируемый", "тип системы":  │
│      ┆                                                           ┆ автомобили"}                                              ┆            ┆ "легковые автомобили"}                                   │
│ 427  ┆ комплект подшипника ступицы колеса lynxauto               ┆ {"артикул производителя":"","бренд":"lynxauto","примечани ┆ Автотовары ┆ {"артикул производителя": "", "бренд": "lynxauto",       │
│      ┆                                                           ┆ е":"внешний вид изделия может отличаться от               ┆            ┆ "примечание": "внешний вид изделия может отличаться от   │
│      ┆                                                           ┆ фотографий","цена за":"1 шт.","код                        ┆            ┆ фотографий", "плата за": "1 шт.", "код товара":          │
│      ┆                                                           ┆ товара":"600000256748"}                                   ┆            ┆ "600000256748"}                                          │
│ 1027 ┆ kraft подшипник ступицы, арт. kt204632, 1 шт.             ┆ {"артикул":"112097-01","бренд":"kraft","количество в      ┆ Автотовары ┆ {"артикул": "112097-01", "бренд": "kraft", "количество в │
│      ┆                                                           ┆ упаковке, шт":"1","партномер (артикул                     ┆            ┆ упаковке, шт": "1", "партномер (артикул производителя)": │
│      ┆                                                           ┆ производителя)":"kt204632","тип":"подшипник ступицы"}     ┆            ┆ "kt204632", "тип": "подшипник ступицы"}                  │
│ 2639 ┆ фильтр салонный skoda fabia 00-                           ┆ {"альтернативные артикулы товара":"8104400xkz96a;50013702 ┆ Автотовары ┆ {"альтернативные артикулы товара": "8104400xkz96a;500137 │
│      ┆                                                           ┆ ;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403;ca- ┆            ┆ 02;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403; │
│      ┆                                                           ┆ 49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010-026 ┆            ┆ ca-49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010 │
│      ┆                                                           ┆ ;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545;if30 ┆            ┆ -026;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545 │
│      ┆                                                           ┆ 19k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac ┆            ┆ ;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx0 │
│      ┆                                                           ┆ -1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;w ┆            ┆ 55;lac-1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cu │
│      ┆                                                           ┆ c4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e ┆            ┆ k2545;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2 │
│      ┆                                                           ┆ 4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a\n","арти ┆            ┆ 123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a │
│      ┆                                                           ┆ кул":"cu2545","бренд":"sat","страна-изготовитель":"китай" ┆            ┆ ", "артикул": "cu2545", "бренд": "sat",                  │
│      ┆                                                           ┆ ,"oem-номер":"8104400xkz96a;50013702;ac0110c;50013941;9.7 ┆            ┆ "страна-производитель": "китай", "oem-номер": "8104400xk │
│      ┆                                                           ┆ .84;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;fs08 ┆            ┆ z96a;50013702;ac0110c;50013941;9.7.84;la120;if-3019;afc1 │
│      ┆                                                           ┆ 9;lak120;sab 123;1987432057;1010-026;6q0819653;6q0819653b ┆            ┆ 076;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987 │
│      ┆                                                           ┆ ;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;af ┆            ┆ 432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c;fs- │
│      ┆                                                           ┆ w1076;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;71102 ┆            ┆ 089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21 │
│      ┆                                                           ┆ 47sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q ┆            ┆ f061;jdacx055;lac-1006;7110221sx;7110247sx;1cf031;nfe-23 │
│      ┆                                                           ┆ 0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf ┆            ┆ 89;k1079;cuk2545;wc4015;7110543sx;st-6q0820367b;nf6123c; │
│      ┆                                                           ┆ 2041;lac1006c;8104400xkz96a\n","комплектация":"фильтр     ┆            ┆ sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;81 │
│      ┆                                                           ┆ салона для авто 1 шт","партномер (…                       ┆            ┆ 04400xkz96a", "комплект": "фильтр салона для авто 1 шт", │
│      ┆                                                           ┆                                                           ┆            ┆ "партно…                                                 │
└──────┴───────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────┴────────────┴──────────────────────────────────────────────────────────┘

In [34]:
df_human.sample().head()

shape: (1, 5)
┌──────────────┬───────────────┬──────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────────────────────────────────────────────────────────────┐
│ id           ┆ name          ┆ attributes                                                                   ┆ category ┆ normalized_attributes                                                       │
│ ---          ┆ ---           ┆ ---                                                                          ┆ ---      ┆ ---                                                                         │
│ i64          ┆ str           ┆ str                                                                          ┆ str      ┆ str                                                                         │
╞══════════════╪═══════════════╪══════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════════════════════════════════════════════════════════════╡
│ 180388640587 ┆ кеды tendance ┆ {"целевая аудитория":"взрослая","бренд в одежде и обуви":"tendance","страна  ┆ Обувь    ┆ {"целевая аудитория": "взрослая", "бренд в одежде и обуви": "tendance",     │
│              ┆               ┆ бренда":"франция","коллекция":"базовая коллекция","цвет                      ┆          ┆ "страна бренда": "франция", "коллекция": "базовая коллекция", "цвет         │
│              ┆               ┆ товара":"темно-бежевый","страна-изготовитель":"китай","материал подкладки    ┆          ┆ товара": "темно-бежевый", "страна-производитель": "китай", "материал        │
│              ┆               ┆ обуви":"натуральная кожа","материал верха":"натуральная                      ┆          ┆ подкладки обуви": "натуральная кожа", "материал высота": "натуральная       │
│              ┆               ┆ кожа","материал":"натуральная кожа","российский                              ┆          ┆ кожа", "материал": "натуральная кожа", "российский количество": "39",       │
│              ┆               ┆ размер":"39","сезон":"демисезон","пол":"женский","высота подошвы,            ┆          ┆ "сезон": "демисезон", "пол": "женский", "высота подошвы, см": "2.5",        │
│              ┆               ┆ см":"2.5","материал подошвы обуви":"резина"}                                 ┆          ┆ "материал подошвы обуви": "резина"}                                         │
└──────────────┴───────────────┴──────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────────────────────────────────────────────────────────────┘

In [35]:
df_human = pd.read_parquet(items_human_path)
df_human.head()

,id,name,attributes,category,normalized_attributes
0,197,victor reinz прокладка впускного коллектора ар...,"{""артикул"":""703315700"",""бренд"":""victor reinz"",...",Автотовары,"{""артикул"": ""703315700"", ""бренд"": ""victor rein..."
1,415,"stellox диск тормозной, арт. 8500892sx","{""артикул"":""stellox_8500892sx"",""место установк...",Автотовары,"{""артикул"": ""stellox_8500892sx"", ""система уста..."
2,427,комплект подшипника ступицы колеса lynxauto,"{""артикул производителя"":"""",""бренд"":""lynxauto""...",Автотовары,"{""артикул производителя"": """", ""бренд"": ""lynxau..."
3,1027,"kraft подшипник ступицы, арт. kt204632, 1 шт.","{""артикул"":""112097-01"",""бренд"":""kraft"",""количе...",Автотовары,"{""артикул"": ""112097-01"", ""бренд"": ""kraft"", ""ко..."
4,2639,фильтр салонный skoda fabia 00-,"{""альтернативные артикулы товара"":""8104400xkz9...",Автотовары,"{""альтернативные артикулы товара"": ""8104400xkz..."

In [36]:
for index, row in df_human.head().iterrows():
    # Process each row
    attrs = json.loads(row['attributes'])
    print(attrs)
    attr_text = " ".join([f"{k}: {v}" for k, v in attrs.items()])
    print(attr_text)

{'артикул': '703315700', 'бренд': 'victor reinz', 'партномер (артикул производителя)': '703315700', 'тип': 'прокладка двигателя', 'вид техники': 'легковые автомобили'}
артикул: 703315700 бренд: victor reinz партномер (артикул производителя): 703315700 тип: прокладка двигателя вид техники: легковые автомобили
{'артикул': 'stellox_8500892sx', 'место установки': 'передние', 'толщина тормозного диска, мм': '28', 'бренд': 'stellox', 'oem-номер': '3050086; a9064210012; 2e0615301; 68006716aa; 9064210012; 9064210212; 9064210012s; 9064210112', 'партномер (артикул производителя)': '8500892sx', 'тип': 'диск тормозной', 'тип тормозного диска': 'вентилируемый', 'вид техники': 'легковые автомобили'}
артикул: stellox_8500892sx место установки: передние толщина тормозного диска, мм: 28 бренд: stellox oem-номер: 3050086; a9064210012; 2e0615301; 68006716aa; 9064210012; 9064210212; 9064210012s; 9064210112 партномер (артикул производителя): 8500892sx тип: диск тормозной тип тормозного диска: вентилируемый вид техники: легковые автомобили
{'артикул производителя': '', 'бренд': 'lynxauto', 'примечание': 'внешний вид изделия может отличаться от фотографий', 'цена за': '1 шт.', 'код товара': '600000256748'}
артикул производителя:  бренд: lynxauto примечание: внешний вид изделия может отличаться от фотографий цена за: 1 шт. код товара: 600000256748
{'артикул': '112097-01', 'бренд': 'kraft', 'количество в упаковке, шт': '1', 'партномер (артикул производителя)': 'kt204632', 'тип': 'подшипник ступицы'}
артикул: 112097-01 бренд: kraft количество в упаковке, шт: 1 партномер (артикул производителя): kt204632 тип: подшипник ступицы
{'альтернативные артикулы товара': '8104400xkz96a;50013702;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a\n', 'артикул': 'cu2545', 'бренд': 'sat', 'страна-изготовитель': 'китай', 'oem-номер': '8104400xkz96a;50013702;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a\n', 'комплектация': 'фильтр салона для авто 1 шт', 'партномер (артикул производителя)': 'cu2545', 'единиц в одном товаре': '1', 'тип': 'фильтр салонный', 'вид техники': 'легковые автомобили'}
альтернативные артикулы товара: 8104400xkz96a;50013702;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a
 артикул: cu2545 бренд: sat страна-изготовитель: китай oem-номер: 8104400xkz96a;50013702;ac0110c;50013941;9.7.84;la120;if-3019;afc1076;ac9403;ca-49010;6q0820367b;fs089;lak120;sab 123;1987432057;1010-026;6q0819653;6q0819653b;9.7.147;ac0110c;fs-089;dfc2545;if3019k;if3019p;sa1123;afw1076;gb9892c;fcr21f061;jdacx055;lac-1006;7110221sx;7110247sx;1cf031;nfe-2389;k1079;cuk2545;wc4015;7110543sx;st-6q0820367b;nf6123c;sa 1123;pf2123;mc-e4072;nf6123;1cf041;pf2041;lac1006c;8104400xkz96a
 комплектация: фильтр салона для авто 1 шт партномер (артикул производителя): cu2545 единиц в одном товаре: 1 тип: фильтр салонный вид техники: легковые автомобили